from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():

    # Define the topic for the correctly stamped PointCloud2 data
    stamped_cloud_topic = '/cloud_xyz_stamped'
    odom_topic = '/odom'

    return LaunchDescription([

        # 1. Point Cloud Stamper (Fixes the Empty Frame ID Error)
        # It takes the raw cloud and publishes it with the required 'velodyne_link' frame_id.
        Node(
            package='rtabmap_util',
            executable='point_cloud_xyz',
            name='point_cloud_xyz_stamper', 
            output='screen',
            remappings=[
                ('cloud_in', '/fw_max/points_raw'),
                ('cloud', stamped_cloud_topic) # Outputting the fixed cloud here
            ],
            parameters=[{
                "frame_id": "velodyne_link" # CRITICAL: Manually set the frame ID
            }]
        ),

        # 2. RTAB-Map 3D SLAM (Optimized for Lidar Odometry)
        Node(
            package='rtabmap_slam',
            executable='rtabmap',
            name='rtabmap',
            output='screen',
            parameters=[{
                'frame_id': 'base_link',
                'subscribe_scan_cloud': True,

                # Lidar SLAM Configuration
                'subscribe_odom': False,            # Do not subscribe to external odometry
                'subscribe_rgb': False,             # Disable camera inputs
                'subscribe_depth': False,
                'Reg/Strategy': '1',                # Use ICP (Lidar Odometry)
                'scan_cloud_frame_id': 'velodyne_link', 

                # Mapping Output Settings
                'Rtabmap/DetectionRate': '1.0',
                'Grid/FromDepth': False,
                'publish_map_cloud': True           # Ensure /cloud_map is published
            }],
            remappings=[
                # Subscribe to the corrected, stamped cloud
                ('scan_cloud', stamped_cloud_topic), 
            ]
        ),

        # 3. RTAB-Map visualizer
        Node(
            package='rtabmap_viz',
            executable='rtabmap_viz',
            name='rtabmap_viz',
            output='screen',
            parameters=[{
                # Tell the visualizer where to find the odometry generated by the SLAM node
                'odom_topic': odom_topic, 
            }],
            remappings=[
                # Use the corrected, stamped cloud for visualization
                ('scan_cloud', stamped_cloud_topic),
            ]
        )
    ])